trigger : none

pool:
  vmImage: 'ubuntu-16.04'

stages:
-stage: firststage
 jobs:
   -job: firstjob
    strategy:
      maxParallel: 0
      matrix:
        JOB1:
          Version: 1
          AppName: one
        JOB2:
          Version: 2
          AppName: two
        JOB3:
          Version: 3
          AppName: three
    steps:
    -script:
      echo "$(Version)"
      echo "$(AppName)"
     displayName: "Echo Variables"
